# Generated by Django 5.2.4 on 2025-08-13 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVOperation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.TextField()),
                ("input_params", models.JSONField(default=list)),
                ("output_params", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "cv_operations",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("text_region", "text_region"), ("ocr", "ocr")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "datasets",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("config", models.JSONField(default=dict)),
                ("status", models.CharField(default="offline", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("yolo_v5", "yolo_v5"),
                            ("yolo_v8", "yolo_v8"),
                            ("yolo_v9", "yolo_v9"),
                            ("yolo_v10", "yolo_v10"),
                            ("yolo_11", "yolo_11"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "not_started"),
                            ("training", "training"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "models",
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("pipeline_metadata", models.JSONField(default=dict)),
                ("input_params", models.JSONField(default=list)),
                ("output_params", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "pipelines",
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="backend_re.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "annotations",
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "pass"),
                            ("fail", "fail"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "image_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "processed_image_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("operation_id", models.IntegerField(blank=True, null=True)),
                (
                    "operation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detection_metadata", models.JSONField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="backend_re.device",
                    ),
                ),
            ],
            options={
                "db_table": "detections",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("error", "error"),
                            ("warning", "warning"),
                            ("info", "info"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="backend_re.device",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_annotated", models.BooleanField(default=False)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="backend_re.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=1000)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "key"), name="uq_settings_category_key"
                    )
                ],
            },
        ),
    ]
