# Generated by Django 5.2.5 on 2025-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_re', '0003_model_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='architecture',
        ),
        migrations.AddField(
            model_name='model',
            name='_architecture',
            field=models.CharField(choices=[('yolo_v8', 'yolo_v8'), ('yolo_v9', 'yolo_v9'), ('yolo_v10', 'yolo_v10'), ('yolo_11', 'yolo_11'), ('yolo_v5', 'yolo_v5')], db_column='architecture', default='yolo_v8', max_length=20),
            preserve_default=False,
        ),
    ]
