# Generated by Django 5.2.5 on 2025-08-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_re', '0004_remove_model_architecture_model__architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='backend_re.image'),
        ),
    ]
