# Generated by Django 4.1.10 on 2024-03-18 16:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import common.encoder.encoder

def insert_default_data(apps, schema_editor):
    TeamModel = apps.get_model('setting', 'Team')
    TeamModel.objects.create(user_id='f0dd8f71-e4ee-11ee-8c84-a8a1595801ab', name='admin的团队')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False,
                                      to='users.user', verbose_name='团队所有者')),
                ('name', models.CharField(max_length=128, verbose_name='团队名称')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.RunPython(insert_default_data),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False,
                                        verbose_name='主键id')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setting.team',
                                           verbose_name='团队id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user',
                                           verbose_name='成员用户id')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberPermission',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False,
                                        verbose_name='主键id')),
                ('auth_target_type',
                 models.CharField(choices=[('DATASET', '数据集'), ('APPLICATION', '应用')], default='DATASET',
                                  max_length=128, verbose_name='授权目标')),
                ('target', models.UUIDField(verbose_name='数据集/应用id')),
                ('operate', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, choices=[('MANAGE', '管理'), ('USE', '使用')],
                                                default='USE', max_length=256), size=None,
                    verbose_name='权限操作列表')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='setting.teammember',
                                             verbose_name='团队成员')),
            ],
            options={
                'db_table': 'team_member_permission',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('menu', models.CharField(max_length=128, verbose_name='操作菜单')),
                ('operate', models.CharField(max_length=128, verbose_name='操作')),
                ('operation_object', models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='操作对象')),
                ('user', models.JSONField(default=dict, verbose_name='用户信息')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('ip_address', models.CharField(max_length=128, verbose_name='ip地址')),
                ('details', models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder, verbose_name='详情')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('type', models.IntegerField(choices=[(0, '邮箱'), (1, '私钥秘钥')], default=0, primary_key=True, serialize=False, verbose_name='设置类型')),
                ('meta', models.JSONField(default=dict, verbose_name='配置数据')),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
