# Generated by Django 5.2.4 on 2025-08-12 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammemberpermission",
            old_name="operate",
            new_name="operate_field",
        ),
    ]
